In [1]:
import h5py

path = '../data/train/data.h5py'

In [2]:
hdf5_data = h5py.File(path, 'r')
a_group_key = list(hdf5_data.keys())
a_group_key

['dev', 'train']

In [3]:
list(hdf5_data['train'].keys())

['aging', 'b2v', 'img_feat', 'pid', 'price_lev', 'tag', 'y']

In [4]:
for key in list(hdf5_data['dev'].keys()):
    print(hdf5_data['dev'][key][15])

0.03228621
[ 0.16803625  0.01089094 -0.16927046  0.03881412  0.23232915  0.09288245
  0.01375257 -0.19623938 -0.12775795 -0.02809932  0.39528012 -0.1698857
 -0.16688354 -0.23523253 -0.08946232 -0.28542584  0.02014689 -0.15149663
  0.26537284  0.03164014  0.12827942 -0.03206663 -0.34036526  0.13716283
  0.105431    0.19988051  0.15617195 -0.2572644  -0.16568571 -0.279184
 -0.02924136  0.09150377 -0.19054179  0.249625   -0.24728763  0.27933216
  0.33393976 -0.08646668 -0.08131811  0.12907867  0.05323661  0.23242517
 -0.49343735  0.00210832  0.29504186  0.49677578 -0.03066224  0.12298175
 -0.09591178  0.00727243  0.14713861 -0.23709533  0.17196156 -0.10234645
  0.12900132 -0.04728572  0.02595643  0.05785054 -0.11923613  0.00872327
  0.06711186 -0.06027145 -0.50030005 -0.20360768 -0.05540701  0.04635401
 -0.19208913  0.07435983 -0.03506575 -0.25216362 -0.3748328   0.1572714
 -0.07853958  0.22845544  0.15553892 -0.11677377 -0.0636617   0.2847253
 -0.16933915  0.11035791 -0.01236503 -0.35419

In [48]:
import numpy as np

a = np.array([[2,3,1], [1,6,8]])
b = np.array([4,5])
b = np.reshape(b, (b.shape[0], 1))
print(a.shape)
print(b.shape)
print(a)
print(b)

np.hstack((a, b))

(2, 3)
(2, 1)
[[2 3 1]
 [1 6 8]]
[[4]
 [5]]


array([[2, 3, 1, 4],
       [1, 6, 8, 5]])

In [71]:
b
encoded = np.zeros((b.shape[0], 5), )

In [72]:
encoded

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
for i in range(0,2):
    encoded[i][b[i]-1] = 1

In [74]:
encoded

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])