## Train dataset Test

In [1]:
import h5py

path = '../data/train/data.h5py'

In [2]:
hdf5_data = h5py.File(path, 'r')
a_group_key = list(hdf5_data.keys())
a_group_key

['dev', 'train']

In [3]:
list(hdf5_data['train'].keys())

['aging', 'b2v', 'img_feat', 'pid', 'price_lev', 'tag', 'y']

In [4]:
for key in list(hdf5_data['dev'].keys()):
    print(hdf5_data['dev'][key][15])

0.03228621
[ 0.16803625  0.01089094 -0.16927046  0.03881412  0.23232915  0.09288245
  0.01375257 -0.19623938 -0.12775795 -0.02809932  0.39528012 -0.1698857
 -0.16688354 -0.23523253 -0.08946232 -0.28542584  0.02014689 -0.15149663
  0.26537284  0.03164014  0.12827942 -0.03206663 -0.34036526  0.13716283
  0.105431    0.19988051  0.15617195 -0.2572644  -0.16568571 -0.279184
 -0.02924136  0.09150377 -0.19054179  0.249625   -0.24728763  0.27933216
  0.33393976 -0.08646668 -0.08131811  0.12907867  0.05323661  0.23242517
 -0.49343735  0.00210832  0.29504186  0.49677578 -0.03066224  0.12298175
 -0.09591178  0.00727243  0.14713861 -0.23709533  0.17196156 -0.10234645
  0.12900132 -0.04728572  0.02595643  0.05785054 -0.11923613  0.00872327
  0.06711186 -0.06027145 -0.50030005 -0.20360768 -0.05540701  0.04635401
 -0.19208913  0.07435983 -0.03506575 -0.25216362 -0.3748328   0.1572714
 -0.07853958  0.22845544  0.15553892 -0.11677377 -0.0636617   0.2847253
 -0.16933915  0.11035791 -0.01236503 -0.35419

## n-d array Test

In [48]:
import numpy as np

a = np.array([[2,3,1], [1,6,8]])
b = np.array([4,5])
b = np.reshape(b, (b.shape[0], 1))
print(a.shape)
print(b.shape)
print(a)
print(b)

np.hstack((a, b))

(2, 3)
(2, 1)
[[2 3 1]
 [1 6 8]]
[[4]
 [5]]


array([[2, 3, 1, 4],
       [1, 6, 8, 5]])

In [71]:
b
encoded = np.zeros((b.shape[0], 5), )

In [72]:
encoded

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
for i in range(0,2):
    encoded[i][b[i]-1] = 1

In [74]:
encoded

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## print Dict

In [1]:
from six.moves import cPickle

y_vocab = cPickle.loads(open("../data/y_vocab.py3.cPickle", 'rb').read())

In [2]:
y_vocab

{'14>13>235>-1': 0,
 '51>545>-1>-1': 1,
 '28>47>1356>-1': 2,
 '30>195>2378>-1': 3,
 '56>503>3179>227': 4,
 '54>551>3149>-1': 5,
 '30>273>512>-1': 6,
 '34>409>1340>-1': 7,
 '2>66>685>-1': 13,
 '25>435>1906>-1': 10,
 '43>109>1576>-1': 11,
 '40>100>951>-1': 14,
 '35>68>1782>-1': 15,
 '37>159>1155>-1': 17,
 '13>293>3123>-1': 18,
 '28>86>167>-1': 19,
 '15>268>818>-1': 3517,
 '34>439>2696>-1': 20,
 '11>151>1478>-1': 21,
 '44>175>2432>-1': 24,
 '11>220>1617>-1': 23,
 '23>246>-1>-1': 27,
 '44>437>2441>-1': 28,
 '12>234>420>50': 29,
 '24>204>890>-1': 31,
 '44>175>2136>-1': 33,
 '51>240>2905>-1': 34,
 '56>495>2600>227': 2084,
 '41>249>2118>-1': 35,
 '16>19>472>-1': 36,
 '17>179>465>-1': 37,
 '28>47>57>-1': 38,
 '10>476>3148>-1': 39,
 '23>411>1373>-1': 41,
 '41>318>1490>269': 43,
 '9>51>546>-1': 44,
 '25>32>1655>181': 12,
 '22>27>716>-1': 995,
 '8>214>782>-1': 47,
 '56>504>2645>227': 2780,
 '1>336>2422>-1': 49,
 '10>476>2213>-1': 50,
 '24>73>98>-1': 51,
 '28>226>2024>-1': 52,
 '27>370>2707>-1': 5

## Dev dataset Test

In [41]:
import h5py

path = '../data/dev/data.h5py'

In [42]:
hdf5_data = h5py.File(path, 'r')
a_group_key = list(hdf5_data.keys())
a_group_key

['dev', 'train']

In [43]:
list(hdf5_data['dev'].keys())

['aging', 'b2v', 'img_feat', 'pid', 'price_lev', 'tag', 'y']

In [45]:
for key in list(hdf5_data['dev'].keys()):
    print(hdf5_data['dev'][key][1])

0.11295181
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.35443202 0.34282315 0.00083356 ... 0.01640162 0.00861821 0.36898458]
b'J4915447877'
2
1
-1


## Test dataset Test

In [37]:
import h5py

path = '../data/test/data.h5py'

In [38]:
hdf5_data = h5py.File(path, 'r')
a_group_key = list(hdf5_data.keys())
a_group_key

['dev', 'train']

In [39]:
list(hdf5_data['train'].keys())

['aging', 'b2v', 'img_feat', 'pid', 'price_lev', 'tag', 'y']

In [40]:
for key in list(hdf5_data['dev'].keys()):
    print(hdf5_data['dev'][key][0])

0.005263158
[ 0.17714539  0.13378805 -0.26299226 -0.07419741  0.20938317  0.1479634
 -0.01044734 -0.21666281 -0.16818647  0.04732506  0.6032456  -0.3171115
 -0.17188203 -0.28793874 -0.14260983 -0.3064565   0.11434212 -0.02398345
  0.14521804  0.11275308  0.30155924 -0.01959628 -0.38891023  0.21273936
  0.12314367  0.28872043  0.15897222 -0.20225349 -0.12064985 -0.39870512
  0.06673782  0.20508821 -0.3000164   0.28871214 -0.24414003  0.40782127
  0.5086636  -0.14739135 -0.17083608  0.03465206  0.13090959  0.25381833
 -0.5874314  -0.04114643  0.28180343  0.5986118  -0.05256347  0.02434513
 -0.22617741  0.01403785  0.18726102 -0.2306064   0.13234563  0.01284377
  0.25460812  0.07834152  0.06231642  0.0265404  -0.09325863 -0.07655746
  0.05353178 -0.08305991 -0.69486177 -0.39150882 -0.07114609  0.01413832
 -0.27136573  0.12738185 -0.00284393 -0.33563215 -0.4385055   0.2967196
 -0.05509292  0.25849038  0.1913869  -0.22672953 -0.090511    0.31557378
 -0.23779146  0.1314612  -0.03854895 -0.36

In [47]:
import h5py

path = '../../../dataset/test.chunk.01'

hdf5_data = h5py.File(path, 'r')
a_group_key = list(hdf5_data.keys())
a_group_key

['test']

In [48]:
hdf5_data['test']

<HDF5 group "/test" (12 members)>

In [50]:
hdf5_data['test']['pid'][0]

b'P4458299590'